---
- name: Create an S3 bucket with versioning, static web hosting, and public access
  hosts: localhost
  vars:
    bucket_name: mys3bucketreactjs
    aws_region: us-east-1
  tasks:
    - name: Create an S3 bucket
      amazon.aws.s3_bucket:
        name: "{{ bucket_name }}"
        state: present
        region: "{{ aws_region }}"
        website:
          index_document: index.html
          error_document: error.html
        tags:
          example: tag1
      register: s3_result

    - name: Enable versioning on the S3 bucket
      amazon.aws.s3_bucket_versioning:
        name: "{{ bucket_name }}"
        state: enabled
        region: "{{ aws_region }}"

    - name: Print the result
      debug:
        var: s3_result

    - name: Set bucket policy to allow public access
      amazon.aws.s3_bucket_policy:
        bucket: "{{ bucket_name }}"
        policy: "{{ lookup('template', 'policy.json') }}"
