---
- name: Create an S3 bucket with versioning and static website hosting
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - amazon.aws
  vars_files:
    - cred.yml  # Ensure this file contains your AWS credentials
  vars:
    bucket_name: mys3bucketreactjs
    aws_region: us-east-1
    ansible_python_interpreter: /usr/bin/python3.12
    aws_access_key: "{{ lookup('vars', 'aws_access_key') }}"
    aws_secret_key: "{{ lookup('vars', 'aws_secret_key') }}"

  tasks:
    - name: Create an S3 bucket
      amazon.aws.s3_bucket:
        name: "{{ bucket_name }}"
        state: present
        region: "{{ aws_region }}"
        versioning: true
        public_access:
          block_public_policy: false
        tags:
          example: tag1

    - name: Pause for bucket propagation
      pause:
        seconds: 10

    - name: Render the S3 bucket policy from template
      template:
        src: policy.json.j2
        dest: /root/playbook/policy.json  # Temporary file to store rendered policy

    - name: Add policy to bucket
      amazon.aws.s3_bucket:
        name: "{{ bucket_name }}"
        policy: "{{ lookup('file', 'policy.json') }}"

    - name: Print the result of S3 bucket creation
      debug:
        var: s3_result

    - name: Upload index.html to S3 bucket
      community.aws.s3_sync:
        bucket: "{{ bucket_name }}"
        file_root: "dist"   # Path to the directory you want to upload
        include: "*"     # Include all files in the directory
        exclude: "*.json" # Exclude .json files if needed
        mode: "push"

    - name: Enable static website
      community.aws.s3_website:
        name: "{{ bucket_name }}"
        suffix: index.html
        error_key: error/404.html
        state: present
        state: present